export const dummy = {
  dates: { maximum: "2023-04-16", minimum: "2023-02-27" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/wybmSmviUXxlBmX44gtpow5Y9TB.jpg",
      genre_ids: [28, 35, 14],
      id: 594767,
      original_language: "en",
      original_title: "Shazam! Fury of the Gods",
      overview:
        "신들의 힘을 갖게 된 빌리(애셔 앤젤)와 친구들은 각자의 방법으로 슈퍼히어로의 삶을 즐기게 된다. 그러던 그들 앞에 잃어버린 힘을 되찾고자 그리스 여신 헤스페라(헬렌 미렌)와 칼립소(루시 리우)가 나타나게 되고, 세상은 혼돈에 빠지게 되는데…",
      popularity: 7479.031,
      poster_path: "/f5907P7GdAGI22PHNRfqoKCAcDR.jpg",
      release_date: "2023-03-15",
      title: "샤잠! 신들의 분노",
      video: false,
      vote_average: 7,
      vote_count: 916,
    },
    {
      adult: false,
      backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
      genre_ids: [18, 28],
      id: 677179,
      original_language: "en",
      original_title: "Creed III",
      overview:
        "록키의 후계자인 크리드는 월드 챔피언으로 권투계를 장악한 후 완벽한 삶을 살던 중 과거 친형제 같았던 데미안과 재회한다. 오랜 시간 감옥 생활을 마치고 나온 데미안은 그가 꿈꾸던 인생을 사는 크리드와 충돌하며 그의 모든 것을 빼앗으려 하고, 크리드는 이에 맞서 자신의 미래를 지키기 위한 일생일대의 대결을 준비하는데…",
      popularity: 4593.748,
      poster_path: "/56HGRCoEY2OmO1yZro77IvldDpE.jpg",
      release_date: "2023-03-01",
      title: "크리드 3",
      video: false,
      vote_average: 7.3,
      vote_count: 1024,
    },
    {
      adult: false,
      backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
      genre_ids: [28, 53, 80],
      id: 603692,
      original_language: "en",
      original_title: "John Wick: Chapter 4",
      overview:
        "죽을 위기에서 살아난 존 윅은 최고 회의를 쓰러트릴 방법을 찾아낸다. 비로소 완전한 자유의 희망을 보지만, 빌런 그라몽 후작과 전 세계의 최강 연합은 존 윅의 오랜 친구까지 적으로 만들어 버리고, 새로운 위기에 놓인 존 윅은 최후의 반격을 준비하는데...",
      popularity: 1988.39,
      poster_path: "/9WF6TxCYwdiZw51NM92ConaQz1w.jpg",
      release_date: "2023-04-12",
      title: "존 윅 4",
      video: false,
      vote_average: 8,
      vote_count: 1078,
    },
    {
      adult: false,
      backdrop_path: "/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
      genre_ids: [27, 53],
      id: 980078,
      original_language: "en",
      original_title: "Winnie the Pooh: Blood and Honey",
      overview:
        "어릴 적 친구로부터 버림받은 곰돌이 ‘푸’와 ‘피글렛’  참을 수 없는 분노와 배신감을 느끼며 잔혹한 복수를 시작한다.",
      popularity: 1236.373,
      poster_path: "/fcCbzcEbAEQ5gWzx7EX78qLEVFw.jpg",
      release_date: "2023-04-06",
      title: "곰돌이 푸: 피와 꿀",
      video: false,
      vote_average: 5.8,
      vote_count: 456,
    },
    {
      adult: false,
      backdrop_path: "/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
      genre_ids: [28, 12, 53],
      id: 646389,
      original_language: "en",
      original_title: "Plane",
      overview:
        "평소와 다를 것 없던 어느 날, 기장 토렌스는 비행기 운행 중 거대한 폭풍우를 만나 정체모를 섬에 불시착한다. 살아남았다는 기쁨도 잠시, 비행기를 탈취하려는 무장단체의 인질극이 시작되고 토렌스는 탑승객 중 가장 피해야 할 의문의 살인범 가스파레와 손을 잡고 승객들과 함께 탈출을 시도하는데… 무장단체의 표적은 단 하나, 토렌스와 탑승객들! 목숨을 건 위험한 탈출 작전이 시작된다!",
      popularity: 789.657,
      poster_path: "/8XDLgSlM6hb01iEWNRbqxKdFnGD.jpg",
      release_date: "2023-03-15",
      title: "플레인",
      video: false,
      vote_average: 6.9,
      vote_count: 1092,
    },
    {
      adult: false,
      backdrop_path: "/zM9RGbJBZ3UNpFOabcRqh0iVAYP.jpg",
      genre_ids: [27, 9648, 53],
      id: 631842,
      original_language: "en",
      original_title: "Knock at the Cabin",
      overview:
        "휴가를 떠난 한 가족은 별장에 무단침입한 낯선 방문자들과 대치하게 된다. ‘레너드’(데이브 바티스타)와 낯선 방문자들은 세상의 종말을 막으러 왔다며, 가족 중 한 명을 희생시켜야만 인류의 멸망을 막을 수 있다는 잔혹한 선택을 하게 하는데… 가족을 살리면 인류가 멸망하고, 인류를 살리면 가족이 죽는다!",
      popularity: 828.781,
      poster_path: "/mCDSOfcVJfMkGUNrNpXWFO7oNBY.jpg",
      release_date: "2023-03-08",
      title: "똑똑똑",
      video: false,
      vote_average: 6.4,
      vote_count: 1274,
    },
    {
      adult: false,
      backdrop_path: "/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
      genre_ids: [28, 35, 10749],
      id: 758009,
      original_language: "en",
      original_title: "Shotgun Wedding",
      overview:
        "‘다아시’(제니퍼 로페즈)와 ‘톰’(조쉬 더하멜)의 결혼식 당일, 우여곡절 끝에 결혼식에 참석할 모두가 섬에 모인다. 모든 게 순조로워 보이던 그때!  갑자기 들이닥친 해적으로 인해 결혼식장의 모두가 인질이 되고… ‘다아시’와 ‘톰’은 무사히 혼인서약을 마치기 위해 목숨을 건 버진 로드를 걷게 되는데…  죽이든가, 죽든가! 2023년 3월, 가장 화X한 웨딩이 온다!",
      popularity: 563.906,
      poster_path: "/aGhII6CTTvpZwnElzAUB7ZbgjTN.jpg",
      release_date: "2023-03-29",
      title: "샷건 웨딩",
      video: false,
      vote_average: 6.3,
      vote_count: 755,
    },
    {
      adult: false,
      backdrop_path: "/ceYZCBfwbBwSpGJ6PapNVw5jqLG.jpg",
      genre_ids: [16, 18, 12, 14],
      id: 916224,
      original_language: "ja",
      original_title: "すずめの戸締まり",
      overview:
        "큐슈의 작은 마을에서 살고 있는 소녀 ‘스즈메’는 어느 날, 여행을 하며 ‘문’을 찾고 있는 한 청년을 만난다. 그의 뒤를 쫓아간 소녀는 산속 폐허에서 덩그러니 남겨진 낡은 문을 발견한다. 무언가에 이끌린 듯 ‘스즈메’는 문으로 손을 뻗는데…",
      popularity: 418.2,
      poster_path: "/kVS51ssZF1y0IXF342h54cIJ0EK.jpg",
      release_date: "2023-03-08",
      title: "스즈메의 문단속",
      video: false,
      vote_average: 8.1,
      vote_count: 121,
    },
    {
      adult: false,
      backdrop_path: "/2rVkDZFLN6DI5PAoraoe9m4IRMN.jpg",
      genre_ids: [12, 14, 35],
      id: 493529,
      original_language: "en",
      original_title: "Dungeons & Dragons: Honor Among Thieves",
      overview:
        "한때는 명예로운 기사였지만, ‘어떤 사건’ 이후 ‘홀가’, ‘사이먼’, ‘포지’와 함께 도적질을 하게 된 ‘에드긴’. ‘소피나’의 제안으로 ’부활의 서판’을 얻기 위해 ‘코린의 성’에 잠입하지만  ‘포지’와 ‘소피나’의 배신으로 실패하고 감옥에 갇힌다. 기발한 방법으로 탈옥에 성공한 ‘에드긴’과 ‘홀가’는 소중한 사람들과 다시 만나고, ‘부활의 서판’도 되찾기 위해  자신만의 팀을 꾸리기 시작하는데… 옛 동료인 소질 없는 소서러 '사이먼’과 새롭게 합류한 변신 천재 드루이드 '도릭’, 재미 빼고 다 가진 팔라딘 '젠크’까지 어딘가 2% 부족한 오합지졸로 가득한 이 팀, 과연 무사히 모험을 끝마칠 수 있을까?",
      popularity: 412.981,
      poster_path: "/eg4vGqZo1BpjY3ZoCUAGk09Pq7T.jpg",
      release_date: "2023-03-29",
      title: "던전 앤 드래곤: 도적들의 명예",
      video: false,
      vote_average: 7.5,
      vote_count: 408,
    },
    {
      adult: false,
      backdrop_path: "/r7Dfg9aRZ78gJsmDlCirIIlNH3d.jpg",
      genre_ids: [18],
      id: 785084,
      original_language: "en",
      original_title: "The Whale",
      overview:
        "272kg의 거구로 세상을 거부한 채 살아가는 대학 강사 찰리는 남은 시간이 얼마 없음을 느끼고 오랫동안 만나지 못한 10대 딸 엘리를 집으로 초대한다. 그리고, 매일 자신을 찾아와 에세이 한 편을 완성하면 전 재산을 주겠다고 제안한다.",
      popularity: 390.767,
      poster_path: "/q0xV5Lnq30JiegbVGBOvVwrgUDT.jpg",
      release_date: "2023-03-01",
      title: "더 웨일",
      video: false,
      vote_average: 8.1,
      vote_count: 2005,
    },
    {
      adult: false,
      backdrop_path: "/v2LilmCylr3bL9TCZSj6syjowZh.jpg",
      genre_ids: [35, 18],
      id: 937278,
      original_language: "en",
      original_title: "A Man Called Otto",
      overview:
        "모든 것을 포기하려는 ‘오토’(톰 행크스)는 죽고 싶을 타이밍마다 이를 방해하는 이웃들로 분노가 치밀어 오른다. 인생 최악의 순간, 뜻하지 않은 이웃들과의 사건들로 인해 상황은 생각지도 못한 방향으로 흘러가는데…",
      popularity: 302.617,
      poster_path: "/bC0e8GRmi8pHnkXHPbKqUKo9Kxr.jpg",
      release_date: "2023-03-29",
      title: "오토라는 남자",
      video: false,
      vote_average: 7.9,
      vote_count: 1033,
    },
    {
      adult: false,
      backdrop_path: "/fMymfWwgTfXh9RkBCFuaZrdn8Of.jpg",
      genre_ids: [27, 28],
      id: 760204,
      original_language: "en",
      original_title: "The Lair",
      overview:
        "영국 공군 조종사 싱클레어 대위는 아프가니스탄에서 정찰 임무를 수행하던 중에 반군의 스팅어 미사일에 맞아 격추된다. 싱클레어 대위는 사막에서 자신을 생포하려는 반군을 피해 달아나다 소련이 운영하던 비밀 연구소가 있는 지하 벙커에 떨어져 갇힌다. 그곳에서 괴생명체와 조우하고 사투를 벌이다 겨우 벙커를 빠져나온 싱클레어 대위는 아프간 전진 기지에서 파견 나온 미군에 구조된다. 그날 밤 괴물 무리가 미군 기지로 쳐들어오고, 설상가상으로 미군 정보부대 지휘관은 괴물을 말살하기 위해 비핵무기 중 가장 강력한 폭탄인 ‘모압(MOAB)’을 터뜨리려 폭격기를 출동시킨다. 과연 싱클레어와 대원들은 괴물을 제압하고 폭탄을 피해 살아 돌아갈 수 있을 것인가.",
      popularity: 194.317,
      poster_path: "/lG5pPv2IQKB76nQRmmY9EBj1Xre.jpg",
      release_date: "2023-03-23",
      title: "더 벙커",
      video: false,
      vote_average: 5.8,
      vote_count: 98,
    },
    {
      adult: false,
      backdrop_path: "/ndrZYPNv0jKMCO9Ne98vfNxTzkW.jpg",
      genre_ids: [18, 53],
      id: 878375,
      original_language: "en",
      original_title: "On a Wing and a Prayer",
      overview:
        "조종사가 비행기를 조종하다 예기치 않게 사망한 후 가족을 구하기 위해 안전하게 비행기를 조종해야만 하는 한 남자의 이야기",
      popularity: 196.137,
      poster_path: "/wXiLzb5QiibYSDupKKtAi2MSu06.jpg",
      release_date: "2023-04-07",
      title: "온 어 윙 앤드 어 프레이어",
      video: false,
      vote_average: 6.7,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: "/z7IE0Le0g6sRnzuB2VnR2QbbIcP.jpg",
      genre_ids: [18],
      id: 964980,
      original_language: "en",
      original_title: "Air",
      overview:
        "세기의 아이콘을 만든 그들의 실화! 당신이 알고 있는 그 이상의 이야기  1984년, 업계 꼴찌를 벗어나지 못하고 있는 나이키는 브랜드의 간판이 되어 줄 새로운 모델을 찾는다. 나이키의 스카우터 소니 바카로(맷 데이먼)는 NBA의 떠오르는 루키 마이클 조던이 나이키의 미래라고 생각한다. 그런데, 이미 시장을 장악한 컨버스와 아디다스가 그와의 계약을 노리는 상황 나이키 팀은 조던의 마음을 얻기 위한 전략을 세우는데….",
      popularity: 186.191,
      poster_path: "/u72FzpfOZLBkeUdL3o3jyYK9OxU.jpg",
      release_date: "2023-04-05",
      title: "에어",
      video: false,
      vote_average: 7.7,
      vote_count: 156,
    },
    {
      adult: false,
      backdrop_path: "/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg",
      genre_ids: [28, 12, 878],
      id: 545611,
      original_language: "en",
      original_title: "Everything Everywhere All at Once",
      overview:
        "남편과 세탁소를 운영하며 근근히 살아가고 있는 이민자 이블린 왕. 20대 시절 남편과 순수한 사랑을 불태우며 모든 것을 뒤로 하고 미국으로 이민을 떠났지만, 50대가 된 지금은 세탁소 운영 등 온갖 일로 허덕이며 단란했던 가족과도 삐그덕거리는 등 고달프게 살고 있다. 세무조사를 받던 중 자신이 멀티버스의 여러 다른 자신들과 연결되어 있음을 알게 되고, 강력한 악의 기운으로부터 모든 우주와 가족을 구해내기 위한 모험에 나서게 되는데...",
      popularity: 164.995,
      poster_path: "/aCW0sC55bFnOaUBP2eUGryvAJXf.jpg",
      release_date: "2022-10-12",
      title: "에브리씽 에브리웨어 올 앳 원스",
      video: false,
      vote_average: 7.9,
      vote_count: 4428,
    },
    {
      adult: false,
      backdrop_path: "/2qr4TxR8eIKz1YIwLHMtltzUUc2.jpg",
      genre_ids: [28, 878, 53],
      id: 872177,
      original_language: "en",
      original_title: "Corrective Measures",
      overview:
        "그레이트노스웨스트 지역에 위치한 샌티부론 교도소는 초능력자 죄수들을 가두기 위해 세워진 곳으로 온갖 괴물, 사이보그 그리고 돌연변이들이 넘쳐난다. 그중에 가장 악명 높은 죄수는 추적할 수 없는 재산을 가진 슈퍼 천재 '러브'이다. 부정부패의 온상인 교도소 총책임자 데블린의 유일한 관심은 러브의 숨겨진 재산이다. 이 교도소의 불안한 평화는 불온한 의도로 교도소에 잠입한 살인 자경단 페이백과 날조된 형량을 받은 디에고 도벌이 등장하면서 위기에 처한다. 수감자와 간수들 사이에 긴장이 고조되면서 교도소는 무정부 상태가 되고 질서는 발칵 뒤집힌다.",
      popularity: 113.719,
      poster_path: "/fAKWgJxfmogyXEcae7lGkC39GvX.jpg",
      release_date: "2023-04-05",
      title: "뮤턴트 이스케이프",
      video: false,
      vote_average: 5.2,
      vote_count: 49,
    },
    {
      adult: false,
      backdrop_path: "/eSSZgM4vMcA4XK2FPptLa9NFsAs.jpg",
      genre_ids: [18, 10749],
      id: 617882,
      original_language: "ko",
      original_title: "소울메이트",
      overview:
        "유년 시절을 함께한 미소와 하은이 어른이 되어가는 과정에서 겪는 관계의 굴곡을 그린다. 둘만의 안온한 세계는 10대 후반 무렵, 하은이 동급생 진우와 첫사랑을 시작하면서 미세한 균열을 겪는다. 자유분방한 미소는 도시로 떠나 모험적인 삶을 좇고, 하은은 고향에 남아 안정된 생활을 꾸리면서 둘은 그렇게 점차 멀어진다. 첫 만남부터 서로를 알아본 두 친구 미소와 하은 그리고 진우가 기쁨, 슬픔, 설렘, 그리움까지 모든 것을 함께 한 이야기를 담은 영화.",
      popularity: 127.939,
      poster_path: "/kuhPUschFQTXb7OOfX8J52GLqME.jpg",
      release_date: "2023-03-15",
      title: "소울메이트",
      video: false,
      vote_average: 7,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/dbrLfmFNFEJWv8rLnjpgCKlXWSy.jpg",
      genre_ids: [878, 12, 28],
      id: 333339,
      original_language: "en",
      original_title: "Ready Player One",
      overview:
        "2045년, 암울한 현실과 달리 가상현실 오아시스에서는 누구든 원하는 캐릭터로 상상하는 모든 걸 할 수 있다. 웨이드 와츠의 유일한 낙은 오아시스에 접속하는 것. 어느 날 오아시스의 창시자인 괴짜 천재 제임스 할리데이는 자신이 가상현실 속에 숨겨둔 3개의 미션에서 우승하는 사람에게 오아시스의 소유권과 막대한 유산을 상속한다는 유언을 남기고, 그가 사랑했던 80년대 대중문화 속에 힌트가 있음을 알린다. 와츠가 첫 번째 수수께끼를 푸는 데 성공하자 이를 저지하기 위해 현실에서 살인도 마다하지 않는 IOI라는 거대 기업이 뛰어드는데...",
      popularity: 103.719,
      poster_path: "/j4TIfwFrm8WnckByTnMFEAuIVju.jpg",
      release_date: "2018-03-28",
      title: "레디 플레이어 원",
      video: false,
      vote_average: 7.6,
      vote_count: 13933,
    },
    {
      adult: false,
      backdrop_path: "/1vXD5HXqkhvsXFHE7KmCPZGPR1e.jpg",
      genre_ids: [18, 35],
      id: 674324,
      original_language: "en",
      original_title: "The Banshees of Inisherin",
      overview:
        "아일랜드의 외딴 섬마을 이니셰린. 주민 모두가 인정하는 절친 파우릭과 콜름은 하루도 빠짐없이 함께 술을 마시며 수다를 떨 정도로 다정하고 돈독한 사이다. 어느 날, 돌연 파우릭에게 절교를 선언하는 콜름. 절교를 받아들일 수 없는 파우릭은 그를 찾아가 이유를 묻지만 돌아오는 건 변심한 친구의 차가운 한마디. 관계를 회복해 보려 할수록 상황은 더욱 악화되어 가기만 하고 평온했던 그들의 일상과 마을은 점점 파국으로 치닫는데…",
      popularity: 62.506,
      poster_path: "/o4Qvda5XZV97CTC2UqNiDEBqFnZ.jpg",
      release_date: "2023-03-15",
      title: "이니셰린의 밴시",
      video: false,
      vote_average: 7.5,
      vote_count: 1640,
    },
    {
      adult: false,
      backdrop_path: "/9FwnUYt9mYnXCfhWL6AWymMsfyT.jpg",
      genre_ids: [18, 36],
      id: 854239,
      original_language: "en",
      original_title: "Till",
      overview:
        "1955년 시카고. 엄마 메이미의 사랑을 듬뿍 받고 자란 14살 흑인 소년 에밋 틸은 미국 남부에 사촌을 만나러 갔다가 싸늘한 시신이 되어 돌아온다. 메이미는 에밋의 참혹한 모습을 세상에 공개해 억울한 죽음을 알리기로 결심하는데…",
      popularity: 55.219,
      poster_path: "/gs4rdJAhNZtDS0d9GS129chnWnc.jpg",
      release_date: "2023-03-22",
      title: "틸",
      video: false,
      vote_average: 7.4,
      vote_count: 131,
    },
  ],
  total_pages: 4,
  total_results: 76,
};
